config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :bookmarks do
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
      resources :movies, only: [:index, :show]

    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie, scope: :list
end

app/models/list.rb
class List < ApplicationRecord
    has_many :bookmarks
    has_many :movies, through: :bookmarks, dependent: :destroy

    validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :bookmarks
    has_many :lists, through: :bookmarks

    validates :title, presence: true, uniqueness: true
    validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    def index
      @lists = List.all
    end

    def show
      @list = List.find(params[:id])
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    def index
        @movies = Movie.all
    end

    def show
        @movie = Movie.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="navbar"></div>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Save any kind of movies</h1>
<h2>List</h2>
<ul>
  <% @lists.each do |list| %>
    <li>
      <h3><%= link_to list.name, list_path(list)%></h3>
    </li>
  <% end %>
</ul>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<p><%= link_to "Back to the List", lists_path%></p>

app/views/movies/index.html.erb
<h1>Classic movies</h1>
<p><% @movies %></p>
    <ul>
        <% @movies.each do |movie|%>
            <li>
                <h3><%= link_to movie.title, movie_path(movie)%></h3>
            </li>
        <% end %>
    </ul>

app/views/movies/show.html.erb
<img src="<%=@movie.poster_url %>"%>
<h1><%= @movie.title %></h1>
<p><%= @movie.overview %></h1>
<p><%= link_to "Back to the List", movies_path%></p>